/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY - This class is generated from Payment.avsc
 * To regenerate, run: mvn generate-sources
 */
package com.demo.migration.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Payment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8520994624771508086L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
    "{\"type\":\"record\",\"name\":\"Payment\",\"namespace\":\"com.demo.migration.model\",\"doc\":\"Represents a payment transaction from PoS systems\",\"fields\":[" +
    "{\"name\":\"transactionId\",\"type\":\"string\",\"doc\":\"Unique identifier for the payment transaction\"}," +
    "{\"name\":\"orderId\",\"type\":\"string\",\"doc\":\"Associated order identifier\"}," +
    "{\"name\":\"customerId\",\"type\":\"string\",\"doc\":\"Customer identifier\"}," +
    "{\"name\":\"amount\",\"type\":\"double\",\"doc\":\"Payment amount in the specified currency\"}," +
    "{\"name\":\"currency\",\"type\":\"string\",\"default\":\"USD\",\"doc\":\"Currency code (ISO 4217)\"}," +
    "{\"name\":\"paymentMethod\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentMethod\",\"symbols\":[\"CREDIT_CARD\",\"DEBIT_CARD\",\"DIGITAL_WALLET\",\"BANK_TRANSFER\",\"CASH\"]},\"doc\":\"Method of payment\"}," +
    "{\"name\":\"paymentStatus\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"symbols\":[\"PENDING\",\"AUTHORIZED\",\"CAPTURED\",\"DECLINED\",\"REFUNDED\",\"CANCELLED\"]},\"doc\":\"Current status of the payment\"}," +
    "{\"name\":\"posChannel\",\"type\":{\"type\":\"enum\",\"name\":\"PosChannel\",\"symbols\":[\"WEB\",\"MOBILE_APP\",\"IN_STORE\",\"CALL_CENTER\",\"KIOSK\"]},\"doc\":\"Point of Sale channel where transaction originated\"}," +
    "{\"name\":\"merchantId\",\"type\":\"string\",\"doc\":\"Merchant identifier\"}," +
    "{\"name\":\"merchantName\",\"type\":\"string\",\"doc\":\"Merchant business name\"}," +
    "{\"name\":\"cardLastFour\",\"type\":[\"null\",\"string\"],\"default\":null,\"doc\":\"Last four digits of card (if card payment)\"}," +
    "{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Transaction timestamp in milliseconds since epoch\"}," +
    "{\"name\":\"metadata\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"default\":{},\"doc\":\"Additional key-value metadata\"}" +
    "]}"
  );

  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Payment> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Payment> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  public static BinaryMessageEncoder<Payment> getEncoder() {
    return ENCODER;
  }

  public static BinaryMessageDecoder<Payment> getDecoder() {
    return DECODER;
  }

  public static BinaryMessageDecoder<Payment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter. Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0: return transactionId;
      case 1: return orderId;
      case 2: return customerId;
      case 3: return amount;
      case 4: return currency;
      case 5: return paymentMethod;
      case 6: return paymentStatus;
      case 7: return posChannel;
      case 8: return merchantId;
      case 9: return merchantName;
      case 10: return cardLastFour;
      case 11: return timestamp;
      case 12: return metadata;
      default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader. Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0: transactionId = value$ != null ? value$.toString() : null; break;
      case 1: orderId = value$ != null ? value$.toString() : null; break;
      case 2: customerId = value$ != null ? value$.toString() : null; break;
      case 3: amount = (java.lang.Double)value$; break;
      case 4: currency = value$ != null ? value$.toString() : null; break;
      case 5: paymentMethod = (com.demo.migration.model.PaymentMethod)value$; break;
      case 6: paymentStatus = (com.demo.migration.model.PaymentStatus)value$; break;
      case 7: posChannel = (com.demo.migration.model.PosChannel)value$; break;
      case 8: merchantId = value$ != null ? value$.toString() : null; break;
      case 9: merchantName = value$ != null ? value$.toString() : null; break;
      case 10: cardLastFour = value$ != null ? value$.toString() : null; break;
      case 11: timestamp = (java.lang.Long)value$; break;
      case 12: metadata = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
      default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /** Unique identifier for the payment transaction */
  private java.lang.String transactionId;
  /** Associated order identifier */
  private java.lang.String orderId;
  /** Customer identifier */
  private java.lang.String customerId;
  /** Payment amount in the specified currency */
  private double amount;
  /** Currency code (ISO 4217) */
  private java.lang.String currency;
  /** Method of payment */
  private com.demo.migration.model.PaymentMethod paymentMethod;
  /** Current status of the payment */
  private com.demo.migration.model.PaymentStatus paymentStatus;
  /** Point of Sale channel where transaction originated */
  private com.demo.migration.model.PosChannel posChannel;
  /** Merchant identifier */
  private java.lang.String merchantId;
  /** Merchant business name */
  private java.lang.String merchantName;
  /** Last four digits of card (if card payment) */
  private java.lang.String cardLastFour;
  /** Transaction timestamp in milliseconds since epoch */
  private long timestamp;
  /** Additional key-value metadata */
  private java.util.Map<java.lang.String,java.lang.String> metadata;

  /**
   * Default constructor.
   */
  public Payment() {}

  /**
   * All-args constructor.
   */
  public Payment(java.lang.String transactionId, java.lang.String orderId, java.lang.String customerId, 
                 java.lang.Double amount, java.lang.String currency, com.demo.migration.model.PaymentMethod paymentMethod, 
                 com.demo.migration.model.PaymentStatus paymentStatus, com.demo.migration.model.PosChannel posChannel, 
                 java.lang.String merchantId, java.lang.String merchantName, java.lang.String cardLastFour, 
                 java.lang.Long timestamp, java.util.Map<java.lang.String,java.lang.String> metadata) {
    this.transactionId = transactionId;
    this.orderId = orderId;
    this.customerId = customerId;
    this.amount = amount;
    this.currency = currency;
    this.paymentMethod = paymentMethod;
    this.paymentStatus = paymentStatus;
    this.posChannel = posChannel;
    this.merchantId = merchantId;
    this.merchantName = merchantName;
    this.cardLastFour = cardLastFour;
    this.timestamp = timestamp;
    this.metadata = metadata;
  }

  /**
   * Gets the value of the 'transactionId' field.
   */
  public java.lang.String getTransactionId() {
    return transactionId;
  }

  /**
   * Sets the value of the 'transactionId' field.
   */
  public void setTransactionId(java.lang.String value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }

  /**
   * Sets the value of the 'amount' field.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'currency' field.
   */
  public java.lang.String getCurrency() {
    return currency;
  }

  /**
   * Sets the value of the 'currency' field.
   */
  public void setCurrency(java.lang.String value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'paymentMethod' field.
   */
  public com.demo.migration.model.PaymentMethod getPaymentMethod() {
    return paymentMethod;
  }

  /**
   * Sets the value of the 'paymentMethod' field.
   */
  public void setPaymentMethod(com.demo.migration.model.PaymentMethod value) {
    this.paymentMethod = value;
  }

  /**
   * Gets the value of the 'paymentStatus' field.
   */
  public com.demo.migration.model.PaymentStatus getPaymentStatus() {
    return paymentStatus;
  }

  /**
   * Sets the value of the 'paymentStatus' field.
   */
  public void setPaymentStatus(com.demo.migration.model.PaymentStatus value) {
    this.paymentStatus = value;
  }

  /**
   * Gets the value of the 'posChannel' field.
   */
  public com.demo.migration.model.PosChannel getPosChannel() {
    return posChannel;
  }

  /**
   * Sets the value of the 'posChannel' field.
   */
  public void setPosChannel(com.demo.migration.model.PosChannel value) {
    this.posChannel = value;
  }

  /**
   * Gets the value of the 'merchantId' field.
   */
  public java.lang.String getMerchantId() {
    return merchantId;
  }

  /**
   * Sets the value of the 'merchantId' field.
   */
  public void setMerchantId(java.lang.String value) {
    this.merchantId = value;
  }

  /**
   * Gets the value of the 'merchantName' field.
   */
  public java.lang.String getMerchantName() {
    return merchantName;
  }

  /**
   * Sets the value of the 'merchantName' field.
   */
  public void setMerchantName(java.lang.String value) {
    this.merchantName = value;
  }

  /**
   * Gets the value of the 'cardLastFour' field.
   */
  public java.lang.String getCardLastFour() {
    return cardLastFour;
  }

  /**
   * Sets the value of the 'cardLastFour' field.
   */
  public void setCardLastFour(java.lang.String value) {
    this.cardLastFour = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
    return metadata;
  }

  /**
   * Sets the value of the 'metadata' field.
   */
  public void setMetadata(java.util.Map<java.lang.String,java.lang.String> value) {
    this.metadata = value;
  }

  /**
   * Creates a new Payment RecordBuilder.
   */
  public static com.demo.migration.model.Payment.Builder newBuilder() {
    return new com.demo.migration.model.Payment.Builder();
  }

  /**
   * Creates a new Payment RecordBuilder by copying an existing Payment instance.
   */
  public static com.demo.migration.model.Payment.Builder newBuilder(com.demo.migration.model.Payment other) {
    if (other == null) {
      return new com.demo.migration.model.Payment.Builder();
    } else {
      return new com.demo.migration.model.Payment.Builder(other);
    }
  }

  /**
   * RecordBuilder for Payment instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Payment>
    implements org.apache.avro.data.RecordBuilder<Payment> {

    private java.lang.String transactionId;
    private java.lang.String orderId;
    private java.lang.String customerId;
    private double amount;
    private java.lang.String currency;
    private com.demo.migration.model.PaymentMethod paymentMethod;
    private com.demo.migration.model.PaymentStatus paymentStatus;
    private com.demo.migration.model.PosChannel posChannel;
    private java.lang.String merchantId;
    private java.lang.String merchantName;
    private java.lang.String cardLastFour;
    private long timestamp;
    private java.util.Map<java.lang.String,java.lang.String> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Payment instance
     */
    private Builder(com.demo.migration.model.Payment other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
      }
      if (isValidValue(fields()[2], other.customerId)) {
        this.customerId = data().deepCopy(fields()[2].schema(), other.customerId);
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
      }
      if (isValidValue(fields()[4], other.currency)) {
        this.currency = data().deepCopy(fields()[4].schema(), other.currency);
      }
      if (isValidValue(fields()[5], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[5].schema(), other.paymentMethod);
      }
      if (isValidValue(fields()[6], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[6].schema(), other.paymentStatus);
      }
      if (isValidValue(fields()[7], other.posChannel)) {
        this.posChannel = data().deepCopy(fields()[7].schema(), other.posChannel);
      }
      if (isValidValue(fields()[8], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[8].schema(), other.merchantId);
      }
      if (isValidValue(fields()[9], other.merchantName)) {
        this.merchantName = data().deepCopy(fields()[9].schema(), other.merchantName);
      }
      if (isValidValue(fields()[10], other.cardLastFour)) {
        this.cardLastFour = data().deepCopy(fields()[10].schema(), other.cardLastFour);
      }
      if (isValidValue(fields()[11], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[11].schema(), other.timestamp);
      }
      if (isValidValue(fields()[12], other.metadata)) {
        this.metadata = data().deepCopy(fields()[12].schema(), other.metadata);
      }
    }

    /**
     * Sets the value of the 'transactionId' field.
     */
    public com.demo.migration.model.Payment.Builder setTransactionId(java.lang.String value) {
      validate(fields()[0], value);
      this.transactionId = value;
      return this;
    }

    public boolean hasTransactionId() {
      return true;
    }

    public java.lang.String getTransactionId() {
      return transactionId;
    }

    /**
     * Sets the value of the 'orderId' field.
     */
    public com.demo.migration.model.Payment.Builder setOrderId(java.lang.String value) {
      validate(fields()[1], value);
      this.orderId = value;
      return this;
    }

    public boolean hasOrderId() {
      return true;
    }

    public java.lang.String getOrderId() {
      return orderId;
    }

    /**
     * Sets the value of the 'customerId' field.
     */
    public com.demo.migration.model.Payment.Builder setCustomerId(java.lang.String value) {
      validate(fields()[2], value);
      this.customerId = value;
      return this;
    }

    public boolean hasCustomerId() {
      return true;
    }

    public java.lang.String getCustomerId() {
      return customerId;
    }

    /**
     * Sets the value of the 'amount' field.
     */
    public com.demo.migration.model.Payment.Builder setAmount(double value) {
      validate(fields()[3], value);
      this.amount = value;
      return this;
    }

    public boolean hasAmount() {
      return true;
    }

    public double getAmount() {
      return amount;
    }

    /**
     * Sets the value of the 'currency' field.
     */
    public com.demo.migration.model.Payment.Builder setCurrency(java.lang.String value) {
      validate(fields()[4], value);
      this.currency = value;
      return this;
    }

    public boolean hasCurrency() {
      return true;
    }

    public java.lang.String getCurrency() {
      return currency;
    }

    /**
     * Sets the value of the 'paymentMethod' field.
     */
    public com.demo.migration.model.Payment.Builder setPaymentMethod(com.demo.migration.model.PaymentMethod value) {
      validate(fields()[5], value);
      this.paymentMethod = value;
      return this;
    }

    public boolean hasPaymentMethod() {
      return true;
    }

    public com.demo.migration.model.PaymentMethod getPaymentMethod() {
      return paymentMethod;
    }

    /**
     * Sets the value of the 'paymentStatus' field.
     */
    public com.demo.migration.model.Payment.Builder setPaymentStatus(com.demo.migration.model.PaymentStatus value) {
      validate(fields()[6], value);
      this.paymentStatus = value;
      return this;
    }

    public boolean hasPaymentStatus() {
      return true;
    }

    public com.demo.migration.model.PaymentStatus getPaymentStatus() {
      return paymentStatus;
    }

    /**
     * Sets the value of the 'posChannel' field.
     */
    public com.demo.migration.model.Payment.Builder setPosChannel(com.demo.migration.model.PosChannel value) {
      validate(fields()[7], value);
      this.posChannel = value;
      return this;
    }

    public boolean hasPosChannel() {
      return true;
    }

    public com.demo.migration.model.PosChannel getPosChannel() {
      return posChannel;
    }

    /**
     * Sets the value of the 'merchantId' field.
     */
    public com.demo.migration.model.Payment.Builder setMerchantId(java.lang.String value) {
      validate(fields()[8], value);
      this.merchantId = value;
      return this;
    }

    public boolean hasMerchantId() {
      return true;
    }

    public java.lang.String getMerchantId() {
      return merchantId;
    }

    /**
     * Sets the value of the 'merchantName' field.
     */
    public com.demo.migration.model.Payment.Builder setMerchantName(java.lang.String value) {
      validate(fields()[9], value);
      this.merchantName = value;
      return this;
    }

    public boolean hasMerchantName() {
      return true;
    }

    public java.lang.String getMerchantName() {
      return merchantName;
    }

    /**
     * Sets the value of the 'cardLastFour' field.
     */
    public com.demo.migration.model.Payment.Builder setCardLastFour(java.lang.String value) {
      validate(fields()[10], value);
      this.cardLastFour = value;
      return this;
    }

    public boolean hasCardLastFour() {
      return true;
    }

    public java.lang.String getCardLastFour() {
      return cardLastFour;
    }

    /**
     * Sets the value of the 'timestamp' field.
     */
    public com.demo.migration.model.Payment.Builder setTimestamp(long value) {
      validate(fields()[11], value);
      this.timestamp = value;
      return this;
    }

    public boolean hasTimestamp() {
      return true;
    }

    public long getTimestamp() {
      return timestamp;
    }

    /**
     * Sets the value of the 'metadata' field.
     */
    public com.demo.migration.model.Payment.Builder setMetadata(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[12], value);
      this.metadata = value;
      return this;
    }

    public boolean hasMetadata() {
      return true;
    }

    public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
      return metadata;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Payment build() {
      try {
        Payment record = new Payment();
        record.transactionId = this.transactionId;
        record.orderId = this.orderId;
        record.customerId = this.customerId;
        record.amount = this.amount;
        record.currency = this.currency;
        record.paymentMethod = this.paymentMethod;
        record.paymentStatus = this.paymentStatus;
        record.posChannel = this.posChannel;
        record.merchantId = this.merchantId;
        record.merchantName = this.merchantName;
        record.cardLastFour = this.cardLastFour;
        record.timestamp = this.timestamp;
        record.metadata = this.metadata;
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Payment>
    WRITER$ = (org.apache.avro.io.DatumWriter<Payment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Payment>
    READER$ = (org.apache.avro.io.DatumReader<Payment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }
}
