/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY - This enum is generated from Payment.avsc
 */
package com.demo.migration.model;

@org.apache.avro.specific.AvroGenerated
public enum PaymentStatus implements org.apache.avro.generic.GenericEnumSymbol<PaymentStatus> {
  PENDING, AUTHORIZED, CAPTURED, DECLINED, REFUNDED, CANCELLED;
  
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
    "{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"namespace\":\"com.demo.migration.model\"," +
    "\"symbols\":[\"PENDING\",\"AUTHORIZED\",\"CAPTURED\",\"DECLINED\",\"REFUNDED\",\"CANCELLED\"]}"
  );
  
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
