/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY - This enum is generated from Payment.avsc
 */
package com.demo.migration.model;

@org.apache.avro.specific.AvroGenerated
public enum PaymentMethod implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethod> {
  CREDIT_CARD, DEBIT_CARD, DIGITAL_WALLET, BANK_TRANSFER, CASH;
  
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
    "{\"type\":\"enum\",\"name\":\"PaymentMethod\",\"namespace\":\"com.demo.migration.model\"," +
    "\"symbols\":[\"CREDIT_CARD\",\"DEBIT_CARD\",\"DIGITAL_WALLET\",\"BANK_TRANSFER\",\"CASH\"]}"
  );
  
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
