/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY - This enum is generated from Payment.avsc
 */
package com.demo.migration.model;

@org.apache.avro.specific.AvroGenerated
public enum PosChannel implements org.apache.avro.generic.GenericEnumSymbol<PosChannel> {
  WEB, MOBILE_APP, IN_STORE, CALL_CENTER, KIOSK;
  
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
    "{\"type\":\"enum\",\"name\":\"PosChannel\",\"namespace\":\"com.demo.migration.model\"," +
    "\"symbols\":[\"WEB\",\"MOBILE_APP\",\"IN_STORE\",\"CALL_CENTER\",\"KIOSK\"]}"
  );
  
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
